### ISSUE TITLE
ValueError: Failed to find data adapter that can handle input

### ISSUE THREAD

**Issue by Artchyy** [YerevaNN/mimic3-benchmarks#132]
Hello, 
While trying to train the neurall network for In-hospital mortality prediction this Error occurs: 
```
==> training
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jovyan/mimic3-benchmarks/mimic3models/in_hospital_mortality/main.py", line 157, in <module>
    model.fit(x=train_raw[0],
  File "/opt/conda/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/lib/python3.9/site-packages/keras/engine/data_adapter.py", line 984, in select_data_adapter
    raise ValueError(
ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {"<class 'int'>"})
```

Did anyone had this error as well and found a solution or any ideas what could solve the problem? 
Stackoverflow solutions wasn't very successful 

Thanks in advance!

**Comment by tycui** [comment]
The `val_raw` needs to be converted to NumPy array as well. 

I added 
`train_raw = (np.array(train_raw[0]), np.array(train_raw[1]))` and
`val_raw = (np.array(val_raw[0]), np.array(val_raw[1]))`.
Then it works for me.
