### ISSUE TITLE
decompensation benchmark python script issue

### ISSUE THREAD

**Issue by lordim** [YerevaNN/mimic3-benchmarks#38]
Hello,

I'm running the python script for logistic regression on the decompensation benchmark data. And I'm getting this error:

(ICU_env) oggi2@oggi2-Precision-Tower-7910:/media/oggi2/DATA2/cim_icu/icu_mimic3/mimic3-benchmarks/mimic3models/decompensation/logistic$ python2 -u main.py 
Namespace(epochs=100, features='all', period='all')
==> reading data and extracting features
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    (train_X, train_y) = read_and_extract_features(train_reader, chunk_size)
  File "main.py", line 44, in read_and_extract_features
    ret = common_utils.read_chunk(reader, read_chunk_size)
  File "/media/oggi2/DATA2/cim_icu/mimic3-benchmarks/mimic3models/common_utils.py", line 31, in read_chunk
    ret = reader.read_next()
  File "/media/oggi2/DATA2/cim_icu/mimic3-benchmarks/mimic3benchmark/readers.py", line 33, in read_next
    return self.read_example(to_read_index)
  File "/media/oggi2/DATA2/cim_icu/mimic3-benchmarks/mimic3benchmark/readers.py", line 84, in read_example
    (X, header) = self._read_timeseries(name, t)
  File "/media/oggi2/DATA2/cim_icu/mimic3-benchmarks/mimic3benchmark/readers.py", line 58, in _read_timeseries
    return (np.stack(ret), header)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 353, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

What could be the issue?

**Comment by Harhro94** [comment]
This issue is also solved by [this](https://github.com/YerevaNN/mimic3-benchmarks/commit/46f08bd480683bd28f3f55dadfe35615c4f07157) commit . I have checked the code runs without problems.
