### ISSUE TITLE
Generator Error(s) when trying to train multitask model

### ISSUE THREAD

**Issue by isaacmg** [YerevaNN/mimic3-benchmarks#47]
I have been getting a variety of errors when attempting to train the multitask models the first one I got was this 
```Traceback (most recent call last):
  File "main.py", line 141, in <module>
    shuffle=True)
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3models/multitask/utils.py", line 27, in __init__
    ret = common_utils.read_chunk(reader, N)
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3models/common_utils.py", line 31, in read_chunk
    ret = reader.read_next()
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3benchmark/readers.py", line 35, in read_next
    return self.read_example(to_read_index)
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3benchmark/readers.py", line 336, in read_example
    (X, header) = self._read_timeseries(name)
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3benchmark/readers.py", line 306, in _read_timeseries
    return (np.stack(ret), header)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 353, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

I figured it might be a few bad files so I add a try except statement to just skip those ones. That seemed to solve that problem but then I got another error:

```python Traceback (most recent call last):
  File "main.py", line 141, in <module>
    shuffle=True)
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3-benchmarks/mimic3-benchmarks/mimic3models/multitask/utils.py", line 45, in __init__
    self._preprocess_single(Xs[i], ts[i], ihms[i], decomps[i], loss[i], phenos[i])
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3-benchmarks/mimic3-benchmarks/mimic3models/multitask/utils.py", line 68, in _preprocess_single
    X = self.discretizer.transform(X, end=max_time)[0]
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3-benchmarks/mimic3-benchmarks/mimic3models/preprocessing.py", line 216, in transform
    write(data, bin_id, channel, row[j], begin_pos)
  File "/content/mimic3-benchmarks/mimic3-benchmarks/data/mimic3-benchmarks/mimic3-benchmarks/mimic3-benchmarks/mimic3models/preprocessing.py", line 196, in write
    data[bin_id, begin_pos[channel_id]] = float(value)
ValueError: could not convert string to float: NEG ```

**Comment by Harhro94** [comment]
This error is related to #40 and #41. Commit 46f08bd480683bd28f3f55dadfe35615c4f07157 solves this.  
If you experience this error, please create the benchmark datasets using the latest version of code.
