### ISSUE TITLE
validate_events fails for subjects without events.csv files extracted.

### ISSUE THREAD

**Issue by SeeMJ** [YerevaNN/mimic3-benchmarks#52]
For some of the subjects who don't have events.csv file extracted, validate_events step will fail. 
===============Error message =================
Traceback (most recent call last):
  File "scripts/validate_events.py", line 94, in <module>
    main()
  File "scripts/validate_events.py", line 48, in main
    dtype={'HADM_ID': str, "ICUSTAY_ID": str})
  File "/usr/lib64/python2.7/dist-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib64/python2.7/dist-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/lib64/python2.7/dist-packages/pandas/io/parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "/usr/lib64/python2.7/dist-packages/pandas/io/parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/lib64/python2.7/dist-packages/pandas/io/parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
IOError: File data/root/78819/events.csv does not exist

**Comment by Harhro94** [comment]
Hi @SeeMJ !

This should not have happened. Please make sure the first script finished its work successfully. 
Also, I have updated the whole code today. You can try to create the benchmarks again with the new code, which works with both Python 2 and 3 !

**Comment by turambar** [comment]
Can we close this?
