### ISSUE TITLE
 extract_subjects call is failing with - Overflow in int64 addition

### ISSUE THREAD

**Issue by hsyedsplineai** [YerevaNN/mimic3-benchmarks#71]
Hi,

While running the extract subject command I got the following failure:
OverflowError: Overflow in int64 addition

Can someone suggest some solution. Does it runs only on python2? 
I'm running it using python3.6

The full error message is shown below.
Thanks,
Syed Hussain

========================================================================
>python -m mimic3benchmark.scripts.extract_subjects /home/syed/workmimic/mimic3/ data/root/
START: 61532 57786 46476
REMOVE ICU TRANSFERS: 55830 52834 43277
REMOVE MULTIPLE STAYS PER ADMIT: 50186 50186 41587
Traceback (most recent call last):
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/syed/workmimic/mimic3-benchmarks/mimic3benchmark/scripts/extract_subjects.py", line 49, in <module>
    stays = add_age_to_icustays(stays)
  File "/home/syed/workmimic/mimic3-benchmarks/mimic3benchmark/mimic3csv.py", line 79, in add_age_to_icustays
    stays['AGE'] = (stays.INTIME - stays.DOB).apply(lambda s: s / np.timedelta64(1, 's')) / 60./60/24/365
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py", line 1552, in wrapper
    result = dispatch_to_index_op(op, left, right, pd.DatetimeIndex)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py", line 1191, in dispatch_to_index_op
    result = op(left_idx, right)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py", line 1552, in wrapper
    result = dispatch_to_index_op(op, left, right, pd.DatetimeIndex)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py", line 1191, in dispatch_to_index_op
    result = op(left_idx, right)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/ops.py", line 148, in rsub
    return right - left
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/indexes/datetimelike.py", line 501, in __sub__
    result = self._data.__sub__(maybe_unwrap_index(other))
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/arrays/datetimelike.py", line 1275, in __sub__
    result = self._sub_datetime_arraylike(other)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/arrays/datetimes.py", line 725, in _sub_datetime_arraylike
    arr_mask=arr_mask)
  File "/home/syed/anaconda3/envs/py36/lib/python3.6/site-packages/pandas/core/algorithms.py", line 944, in checked_add_with_arr
    raise OverflowError("Overflow in int64 addition")
OverflowError: Overflow in int64 addition

**Comment by hsyedsplineai** [comment]
Well, I got the same error using python2...

**Comment by hsyedsplineai** [comment]
Seems like I got the solution. It was due to the latest pandas 0.24.2 bug caused from 0.23.* version.
I downgraded it to pandas 0.22 version in my anaconda environment that made the command works.
