### ISSUE TITLE
ValueError: could not convert string to float: '>60/minute'

### ISSUE THREAD

**Issue by congxingzhu** [YerevaNN/mimic3-benchmarks#80]
When running the code **python -um mimic3models.phenotyping.logistic.main --output_dir mimic3models/phenotyping/logistic**, it shows the results like below:

Reading data and extracting features ...
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/phenotyping/logistic/main.py", line 131, in <module>
    main()
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/phenotyping/logistic/main.py", line 58, in main
    (train_X, train_y, train_names, train_ts) = read_and_extract_features(train_reader, args.period, args.features)
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/phenotyping/logistic/main.py", line 20, in read_and_extract_features
    X = common_utils.extract_features_from_rawdata(ret['X'], ret['header'], period, features)
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/common_utils.py", line 27, in extract_features_from_rawdata
    data = [convert_to_dict(X, header, channel_info) for X in chunk]
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/common_utils.py", line 27, in <listcomp>
    data = [convert_to_dict(X, header, channel_info) for X in chunk]
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/common_utils.py", line 20, in convert_to_dict
    ret[i-1] = list(map(lambda x: (float(x[0]), float(x[1])), ret[i-1]))
  File "/Users/congxingzhu/Desktop/CS Project/mimic3-benchmarks/mimic3models/common_utils.py", line 20, in <lambda>
    ret[i-1] = list(map(lambda x: (float(x[0]), float(x[1])), ret[i-1]))
**ValueError: could not convert string to float: '>60/minute'**

Any idea about how to solve this issue?

**Comment by hrayrhar** [comment]
Hi @congxingzhu,

If you still this issue, please check the following two things:

1) That the generated data is correct. You can check this by running the test described [here](https://github.com/YerevaNN/mimic3-benchmarks/tree/master/mimic3benchmark/tests).

2) That you use the intended versions of libraries. See [here](https://github.com/YerevaNN/mimic3-benchmarks/blob/master/requirements.txt).

Hrayr
